#include "data.h"  // Za³adowanie nag³ówka, aby udostêpniæ pytania, odpowiedzi oraz klucz

                                         
										//Tablice zawieraj¹ce pytania, odpowiedzi oraz klucz: 


//Tablica zawieraj¹ca pytania
string questions[71] = { 
						"Polskim odpowiednikiem amerykañskiego baby shower jest:",
						"Æmielów i Chodzie¿ s³yn¹ z produkcji:",
						"Czego zakrêcane wieczko ma taneczn¹ nazwê ?",
						"Do sejmowej zamra¿arki trafiaj¹:",
						"Szejk pije szejka, czyli co:",
						"Komu w 1917 roku Matka Boska przekaza³a trzy tajemnice fatimskie?",
						"Czym by³a zielona ksi¹¿eczka, któr¹ w 2001 roku zast¹pi³a szaro-ró¿owa karta z poliwêglanu?",
						"Jaki ptak ma oczy osadzone frontalnie i otoczone promieniœcie u³o¿onymi piórami?",
						"Gwiazdy, które tworz¹ dyszel Wielkiego Wozu, s¹ jednoczeœnie:",
						"ZnajdŸ b³¹d.",
						"Tempura to panierowane i sma¿one na g³êbokim oleju ryby, krewetki, kalmary, ma³¿e. Sk¹d w XVI wieku przywêdrowa³a do Japonii?",
						"Gdzie bambik zap³aci v-dolcami za skiny?",
						"Trójk¹t Trzech Cesarzy, gdzie od 1846 roku zbiega³y siê granice trzech zaborów, znajduje siê w pobli¿u:",
						"Co wyró¿nia³o ¿yj¹ce w okresie od dewonu do kredy amonity?",
						"Kto w 1954 r. obj¹³ opiek¹ artystyczn¹ gdañski teatr studencki Bim-Bom?",
						"Który œwie¿y owoc zawiera najmniej wody w 100 gramach?",
						"Kto w maju 1848 r. wyst¹pi³ w Londynie przed królow¹ Wiktori¹?",
						"Wystêpuj¹cy w du¿ej liczbie, w wielu formach i odmianach to s³ownikowe znaczenie wyrazu:",
						"Legenda g³osi, ¿e przyczyn ustanowienia przez Edwarda III najwy¿szego brytyjskiego orderu nale¿y upatrywaæ w zgubionej na dworskim balu:",
						"W czym walcz¹ zawodnicy UFC?",
						"W anglojêzycznej korpomowie 'jestem poza biurem' to:",
						"Trójmorze to miêdzynarodowa inicjatywa gospodarczo-polityczna, która skupia 13 pañstw po³o¿onych w pobli¿u trzech mórz: Adriatyckiego, Czarnego i...",
						"W 2023 r. jeden z rodzajów paj¹ków nazwano Abba na czeœæ zespo³u, który przed laty wylansowa³ przebój:",
						"Trzy wyra¿enia dotycz¹ zamêœcia, a jedno nie.",
						"'Halo, halo, Polskie Radio Warszawa, fale 480' - tymi s³owami Janina Sztompkówna rozpoczê³a pierwsz¹ regularn¹ emisjê Polskiego Radia. Kiedy?",
						"Które strony herbu zgodnie z blazonowaniem nie s¹ tymi samymi stronami w rozumieniu patrz¹cego na herb?",
						"O co 'grzecznie, ale stanowczo uprasza liczne zastêpy bliŸnich' Julian Tuwim?",
						"Ile cz³owiek ma koœci stêpu?",
						"Który z muzyków nie zagra³ ani handlarza narkotyków, ani alfonsa, ani agenta Interpolu w serialu 'Policjanci z Miami' ? ",
						"Budowa uk³adu pokarmowego, którego ze zwierz¹t œwiadczy o tym, ¿e jest ono drapie¿nikiem?",
						"Memiczny komentarz do sytuacji, kiedy ktoœ chce zrobiæ coœ, co jest uwa¿ane za niemo¿liwe lub lekkomyœlne, to:",
						"W którym dokumencie po raz pierwszy pojawi³ siê formalny zapis o sto³ecznoœci Warszawy?",
						"Z gry na jakim instrumencie s³ynie Czes³aw Mozil? ",
						"Ró¿añcow¹ tajemnic¹ chwalebn¹ nie jest:",
						"Kiedy rozpoczê³o siê drugie tysi¹clecie?",
						"Do czworonogów, czyli tetrapodów, nie zaliczamy...",
						"XVII-wieczna seria konfliktów miêdzy Lig¹ Katolick¹ a Uni¹ Protestanck¹ trwa³a:",
						"Kandydat na wysokie stanowisko czêsto nie musi mieæ odpowiednich kwalifikacji, o ile ma mocne:",
						"W której z wyp³at ukry³ siê brytyjski grosz?",
						"Sygna³ówka to tr¹bka sygnalistów. Gdzie?",
						"Imperium Inków rozci¹ga³o siê:",
						"Bezpoœrednio po której z wojen powsta³ UNICEF, ¿eby zapewniæ ¿ywotnoœæ i opiekê zdrowotn¹ dla dzieci i matek?",
						"Konduita to prowadzenie siê:",
						"W filmie „Jak zabiæ starsz¹ pani¹” z 1955 r. pieni¹dze z napadu kwintetu smyczkowego na furgonetkê skrywa futera³ na:",
						"Który z gruczo³ów wydziela sok trawienny?",
						"O czym jest piosenka „Prz¹œniczka” Czeczota i Moniuszki?",
						"Które s³owa obs³uguj¹ frazeologicznie sytuacjê bez wyjœcia?",
						"Irina, Masza i Olga z dramatu Antoniego Czechowa z 1900 r. to:",
						"Z tralek sk³ada siê:",
						"Który z nich g³ówn¹ rolê zagra³ tylko w jednym filmie z serii o Jamesie Bondzie?",
						"Zwyczajowo nazywany jest agrestem.",
						"Które to slangowe no pewnie?",
						"Który ptak dzieli nazwê z australijskimi butami z owczej skóry?",
						"Krzywy Róg to miasto w obwodzie dniepropertowskim, czyli:",
						"Inna nazwa tej gry to inteligencja.",
						"Jeœli pokonujemy rzekê w bród, to na pewno:",
						"Perykles, który ¿y³ w V w. p.n.e. w Atenach, uwa¿any jest za ojca:",
						"W jakim utworze Poeta mówi do Gospodarza”(…) a tu pospolitoœæ skrzeczy, a tu pospolitoœæ t³oczy”?",
						"Koniczynka to klasyczny wêze³ typu WA, czyli wêze³:",
						"Jakiej duszy nie ma, kiedy nikogo nie ma?",
						"Geolodzy dziel¹ ska³y na trzy podstawowe grupy. W tym podziale nie ma ska³:",
						"Kapn¹æ to uroniæ kroplê, a kapn¹æ siê:",
						"Co nie jest prawd¹ o kluskach œl¹skich?",
						"U Anglików out of the blue, a u nas:",
						"Co ma odziomek?",
						"Kto jest drugoplanowym bohaterem filmu Paolo Sorrentino „To by³a rêka Boga” z 2021 roku?",
						"Które to sikory?",
						"Laurazja to:",
						"Który turmalin zazwyczaj jest bezbarwny?",
						"Ile g³ównych pór roku jest na sawannie?",
						"Kto w „Trzy po trzy” wspomina³ taki oto napis na transparencie: „O Sasie, w dobrym czasie, drugi raz walisz, przez Kalisz”?",

};

 //Tablica zawieraj¹ca odpowiedzi:
string options[71][4] = {
						{"A: bociankowe", "B: prysznicowe", "C: 500 +", "D: becikowe"},
						{"A: samolotów", "B: leczniczych wód", "C: wagonów kolejowych","D: porcelany"},
						{"A: szkatu³ki", "B: puderniczki", "C: trumienki",  "D: s³oika"},
						{"A: temperamentni pos³owie", "B: skargi na marsza³ka sejmu", "C: projekty niektórych ustaw", "D: nachalni lobbyœci"},
						{"A: potrójne espresso", "B: zielon¹ herbatê", "C: napój mleczno-owocowy", "D: wino gronowe"},
						{"A: skazañcom", "B: pastuszkom", "C: ¿o³nierzom", "D: biskupom"},
						{"A: ksi¹¿eczk¹ oszczêdnoœciow¹", "B: dowodem osobistym", "C: prawem jazdy", "D: ksi¹¿eczk¹ zdrowia"},
						{"A: brzegówka", "B: dymówka", "C: p³omykówka", "D: bogatka"},
						{"A: ogonem Wielkiej NiedŸwiedzicy", "B: kolcem Skorpiona", "C: szyj¹ ¯yrafy", "D: ³ap¹ Lwa"},
						{"A: handlarz starzyzny", "B: handlarz narkotyków", "C: handlarz z³otem", "D: handlarz ¿ywym towarem"},
						{"A: z Holandii", "B: z Portugalii", "C: z Rosji", "D: z Chin"},
						{"A: w 'Fortnite'", "B: w 'Apex Legends'", "C: w 'PUBG'", "D: w 'Call of Duty'"},
						{"A: Gdañska", "B: Szczecina", "C: Katowic", "D: Warszawy"},
						{"A: D³ugie pazury", "B: Spiralne muszle", "C: Kolorowe pióra", "D: P³etwy grzbietowe"},
						{"A: Adolf Dymsza", "B: Zbigniew Cybulski", "C: Jeremi Przybora", "D: Tadeusz £omnicki"},
						{"A: Ananas", "B: Daktyl", "C: Œliwka", "D: Granat"},
						{"A: Artur Rubinstein", "B: Ignacy Paderewski", "C: Karol Szymanowski", "D: Fryderyk Chopin"},
						{"A: Rozliczony", "B: Rozliczaj¹cy", "C: Rozliczeniowy", "D: Rozliczny"},
						{"A: fajce", "B: podwi¹zce", "C: peruce", "D: sakiewce"},
						{"A: w kole", "B: w heksagonie", "C: w pentagonie", "D: w oktagonie"},
						{"A: UUU", "B: OOO", "C: EEE", "D: AAA"},
						{"A: Czerwonego", "B: Ba³tyckiego", "C: Kaspijskiego", "D: Norweskiego"},
						{"A: 'How Deep Is Your Love'", "B: 'Stairway to Heaven'", "C: 'Dancing Queen'", "D: 'Love Me Do'"},
						{"A: wyjœæ za m¹¿", "B: wyjœæ za niego", "C: wyjœæ za ni¹", "D: wydaæ siê za m¹¿"},
						{"A: przed powstaniem styczniowym", "B: przed I wojn¹ œwiatow¹", "C: przed II wojn¹ œwiatow¹", "D: po II wojnie œwiatowej"},
						{"A: dolna i górna", "B: lewa i prawa", "C: tylna i przednia", "D: bierna i czynna"},
						{"A: '¿eby bez przerwy nie plotkowali'", "B: 'o u¿ywanie s³ów odpowiednich'", "C: 'aby go w dupê poca³owali'", "D: 'o szanowanie pañstw s¹siednich'"},
						{"A: dwie", "B: cztery", "C: dwanaœcie", "D: czternaœcie"},
						{"A: Frank Zappa", "B: Miles Davis", "C: Leonard Cohen", "D: Jimi Hendrix"},
						{"A: lamy", "B: koali", "C: pandy", "D: sarny"},
						{"A: 'podtrzymaj mnie na duchu'", "B: 'powstrzymaj siê od uwag'", "C: 'potrzymaj mi piwo'", "D: 'potrzymaj mi marynarkê'"},
						{"A: W konstytucji z 1791 r.", "B: W konstytucji z 1921 r.", "C: W konstytucji z 1952 r.", "D: W konstytucji z 1997 r."},
						{"A: na kornecie", "B: na akordeonie", "C: na djembe", "D: na ksylofonie"},
						{"A: wniebowziêcie Matki Bo¿ej", "B: zmartwychwstanie Jezusa", "C: œmieræ Jezusa na krzy¿u", "D: zes³anie Ducha Œwiêtego"},
						{"A: 1 stycznia 1000 roku", "B: 1 stycznia 1001 roku", "C: 1 stycznia 2000 roku", "D: 1 stycznia 2001 roku"},
						{"A: Gadów", "B: P³azów", "C: Ptaków", "D: Owadów"},
						{"A: 10 lat", "B: 30 lat", "C: 50 lat", "D: 100 lat"},
						{"A: ³ydki", "B: kolana", "C: plecy", "D: rêce"},
						{"A: w honorarium", "B: w wynagrodzeniu", "C: w poborach", "D: w pensji"},
						{"A: na wie¿y mariackiej", "B: w myœlistwie", "C: w korporacjach", "D: w polityce"},
						{"A: na pó³nocy Ameryki Pó³nocnej", "B: na po³udniu Ameryki Pó³nocnej", "C: na wschód od Ameryki Po³udniowej", "D: na zachodzie Ameryki Po³udniowej"},
						{"A: po wojnie secesyjnej", "B: po I wojnie œwiatowej", "C: po II wojnie œwiatowej", "D: po wojnie indochiñskiej"},
						{"A: sportowych Au", "B: wszystkiego wszêdzie i zawsze", "C: prowadnic", "D: ludzi, zw³aszcza podejrzane"},
						{"A: gêœle", "B: fidel p³ock¹", "C: violê da gamba", "D: wiolonczelê"},
						{"A: trzustka", "B: szyszynka", "C: nadnercze", "D: grasica"},
						{"A: o przêdzeniu we³ny", "B: o tkaniu tkaniny", "C: o dzianiu dzianiny", "D: o mi³oœci i zdradzie"},
						{"A: staæ i chrz¹kaæ", "B: kuliæ siê w kucki", "C: le¿eæ i kwiczeæ", "D: bekaæ i beczeæ"},
						{"A: babka, matka i córka", "B: babka i dwie wnuczki", "C: matka i dwie córki", "D: trzy siostry"},
						{"A: aria operowa", "B: balustrada", "C: marionetka", "D: centralka telefoniczna"},
						{"A: Sean Connery", "B: Roger Moore", "C: George Lazenby", "D: Pierce Brosnan"},
						{"A: porzeczka agrest", "B: malina agrest", "C: agrest je¿yna", "D: agrest borówka"},
						{"A: no rejczel", "B: yes ros", "C: no fibi", "D: yes czendler"},
						{"A: ibis", "B: kakadu", "C: emu", "D: lora"},
						{"A: w Ukrainie", "B: na Bia³orusi", "C: na £otwie", "D: w Estonii"},
						{"A: kó³ko i krzy¿yk", "B: wisielec", "C: pañstwa-miasta", "D: okrêty"},
						{"A: nie pieszo", "B: wp³aw", "C: nie ³odzi¹", "D: z du¿ym baga¿em"},
						{"A: demokracji", "B: oligarchii", "C: monarchii", "D: tyranii"},
						{"A: w 'Weselu' Wyspiañskiego", "B: w 'Weselu' Smarzowskiego", "C: w 'Œlubie' Gombrowicza", "D: w '¯onie modnej' Krasickiego"},
						{"A: ¿eglarski", "B: komunikacyjny", "C: radiowy", "D: ch³onny"},
						{"A: ¿ywej", "B: dusznej", "C: uduchowionej", "D: martwej"},
						{"A: osadowych", "B: magmowych", "C: metamorficznych", "D: oceanicznych"},
						{"A: wzi¹æ prysznic", "B: domyœliæ siê", "C: napiæ siê kapkê", "D: napiæ siê kapkê"},
						{"A: s¹ gotowanych ziemniaków", "B: maj¹ dziurkê na wylot", "C: s¹ okr¹g³e", "D: maj¹ wg³êbienie w centrum"},
						{"A: mieæ czegoœ wy¿ej uszu", "B: jak grom z jasnego nieba", "C: mieæ rêkê do kwiatów", "D: miêdzy m³otem a kowad³em"},
						{"A: drzewo", "B: dom z werand¹", "C: ¿aglówkê", "D: piorunochron"},
						{ "A: Pele", "B: Lionel Messi", "C: Robert Lewandowski", "D: Diego Maradona" },
						{"A: zegary wie¿owe", "B: zegarki narêczne", "C: zegary z kuku³k¹", "D: zegary astronomiczne"},
						{"A: miasto w Azji", "B: metropolia nad Laur¹", "C: dawny kontynent", "D: boska ¿ona Gondwany"},
						{"A: achroit", "B: rubelit", "C: verdelit", "D: indigolit"},
						{"A: jedna", "B: dwie", "C: trzy", "D: cztery"},
						{"A: Miko³aj Rej", "B: Adam Mickiewicz", "C: Juliusz S³owacki", "D: Aleksander Fredro"},


};

//Tablica zawieraj¹ca klucz odpowiedzi: 
string key[71] ={
						"A","D","D","C","C","B","B","D","A","A","B","A","C","B","B","B","D",
						"D","C","D","B","C","B","C","C","C","C","D","D","C","C","C","B","C","B",
						"D","B","C","D","B","D","C","D","D","A","D","C","D","B","C","A","A","C","A",
						"C","C","A","A","B","A","D","B","B","B","A","D","B","C","A","B","D" 
};
